//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public int id { get; set; }
        public string ToDo { get; set; }
        public int FirmaId { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual liste liste { get; set; }
    }
}
